version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/deno/Dockerfile
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/root/project
  db:
    image: postgres:alpine
    tty: true
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Password!
      TZ: Asia/Tokyo
